### ISSUE TITLE
[Umbrella] 주요기능 테스트 

### ISSUE THREAD

**Issue by byyoungjin** [heartright-co/expo-bare-test-module_payment#5]
### Front App
- [x] 친구들 연락처 가지고오기 #6 
- [x] 카메라, 앨범기능 #6 
- [x] amplify 연결하기 
- [x] 필요한 animation 효과들 만들어보기 #7

**Comment by byyoungjin** [comment]
## Amplify 이용 앱 구현 구상. #8 
- [x] auth 관리 
- [x] 앱 state 관리 
- [x] db access 패턴 관리

**Comment by byyoungjin** [comment]
## animation 효과들 
reanimated 2  api 가 잘되어있다. 이제막 성숙해진 단계라 어느정도 한계는 있는거 같은데, 전반적으로 적용하는데 무리는 없을듯함.
